### ISSUE TITLE
The particles do not pass through AMI.

### ISSUE THREAD

**Issue by Iseomura** [TonkomoLLC/MPPICInterDyMFoam#4]
Hello, TonkomoLLC

I saw your post and compiled the MPPICInterDyMFoam.
I rotated the propeller and calculated the conditions under which the particles would rise. However, the particles got caught in the AMI and did not rise any further.
I'm using OpenFOAM v2006, and I've read that v2012 will improve the problem, but is it possible to improve it with v2006?

**Comment by TonkomoLLC** [comment]
Dear Iseomura,

I apologize, but I do not know the answer to your question, whether particles will no longer stick to the AMI region when using OpenFOAM v2012. I checked OpenFOAM v2112 for whether the case will run, but I did not run the case to completion.

Further, it is possible that the tutorial case is not set up optimally. It was designed only to test the basic functionality of the solver (i.e., AMI and particles both work).

If you learn anything regarding this matter I hope you will add it to this thread or to CFD-Online. Meanwhile, if I learn anything on this topic I will do the same.

Best regards,

Eric

**Comment by Iseomura** [comment]
Thanks for the reply.
Is it correct that the solver here has tested whether AMI and particles work at the same time?
Does it seem to solve the problem of AMI getting in the way of particles?

**Comment by TonkomoLLC** [comment]
Here is what I ran - up to 0.225 sec - when I tested MPPICInterDyMFoam for OF v2112.  This is the tutorial case on the GitHub repo MPPICInterDyMFoam.

![Time0 225sec](https://user-images.githubusercontent.com/11640748/153761729-f8b24419-12e2-4caf-bcc6-8b69fd732118.png)

I do not think that this test answers your question definitively. It only shows that particles and AMI work together. 

I do not have any further information regarding your question about whether OpenFOAM v2112 solves the problem of AMI getting in the way of particles.

**Comment by Iseomura** [comment]
Thank you.
I will consider it a little more with the v2006 I am using.

**Comment by TonkomoLLC** [comment]
I added a second tutorial case that runs faster. But in the present form the particles fall to the bottom of the tank (starting below the AMI region, so it does not address your question).  Anyhow, this new (faster) tutorial case  may help you test and troubleshoot.

**Comment by TonkomoLLC** [comment]
In case it is helpful, for the second tutorial I modified the starting positions to the attached.  See the attached text file.  
[kinematicCloudPositions.txt](https://github.com/TonkomoLLC/MPPICInterDyMFoam/files/8056136/kinematicCloudPositions.txt)

Some particles start inside the AMI region.

![someParticlesAreInsideAMI](https://user-images.githubusercontent.com/11640748/153765813-405ad64e-b11b-4d8d-a89b-99e0dcc80dce.png)

In the end, particles do NOT get stuck inside the AMI region with OpenFOAM v2112. I did not do this test with OpenFOAM v2106.  I am not 100% sure if this addresses the concern you raised. However, if the concern is that particles inside the AMI region cannot move in or out of the AMI cells, this is certainly not the case with the modified tutorial #2 because all particles by time=1 are at the bottom of the tank (both the particles that start inside and outside the AMI zone).

If this still does not address your concern, then I hope the second tutorial can be a good starting point for exploring the issue you are reporting. Once again, if you learn something new I hope that you will report it here or on CFD-Online

**Comment by TonkomoLLC** [comment]
One more update: 
[kinematicCloudPositions.txt](https://github.com/TonkomoLLC/MPPICInterDyMFoam/files/8056161/kinematicCloudPositions.txt)

The case is not so interesting - the particles fall... but I set the starting point so the particles are inside the AMI region and in the zone where they can be hit by the blades. The particles do not get stuck with OpenFOAM v2112. 

![someParticlesAreInsideAMI](https://user-images.githubusercontent.com/11640748/153766302-d47a0ff7-3e9b-4207-b669-bb3875997f1a.png)


This does not prove for sure that OpenFOAM v2112 is OK, but once again, maybe this second tutorial case can help you.

Good luck!

**Comment by Iseomura** [comment]
Dear TonkomoLLC

Thank you very much! I appreciate your kindness.
I have a feeling that v2112 will be an improvement.

If you don't mind, could you please calculate this propeller for me? Here is the link.

https://drive.google.com/drive/folders/1_VnZCphRkEEMzaSRoatWR0XHhEfUcsns

I have constant, 0.orig, and system in propeller.
The order of calculation is
"surfaceFeatureExtract
blockMesh
snappyHexMesh -overwrite
createBaffles -overwrite
mergeOrSplitBaffles -split -overwrite
  cp -r 0.orig 0 
setFields
MPPICInterDyMFoam".
In v2006, after 2 sec.

In v2006, the result after 2 seconds looks like this. The particles are not rising.
![image](https://user-images.githubusercontent.com/99602255/153785719-2cfb3640-2413-4820-986c-53192da3e961.png)

Please calculate it with V2112 and if the particles are raised, my problem will be completely solved.

Please let me know if there is something wrong with the setting of the calculation conditions or the way the calculation is done.

**Comment by TonkomoLLC** [comment]
Sounds great! I have the case running now. I'll let you know what happens.
Stand by...

**Comment by TonkomoLLC** [comment]
The case stopped at ~0.27 seconds (crashed).  Log is attached.
![Time0 26sec](https://user-images.githubusercontent.com/11640748/153789668-9b8c9db7-f75a-4443-a911-cbe23db4bca3.png)
[error.txt](https://github.com/TonkomoLLC/MPPICInterDyMFoam/files/8057423/error.txt)


I was running in parallel and have restarted the case. I think it is going to fail again because the time steps are becoming very small.

I am restarting the case in serial. If you have any advice please let me know.

**Comment by Iseomura** [comment]
Thank you for running it.
For some reason, when I run parallel calculations, the calculations sometimes fail.
Is it possible to run without decomposePar?

**Comment by TonkomoLLC** [comment]
Thanks for the hint. I am running the case now in serial mode. However, I am located in Arizona, USA where the time is nearly 20:00. This case will not finish until morning my time and I will report on the results then.

**Comment by Iseomura** [comment]
ありがとうございます。
計算していただいているソルバーは数時間かかります。
夜なのにすみません。
返信待ってます。

**Comment by Iseomura** [comment]
Thank you very much.
The solver that you are calculating will take a few hours.
I'm sorry it's night.
I'm waiting for your reply.

**Comment by TonkomoLLC** [comment]
どういたしまして.  朝まで.
(I needed help with Google translate. My Japanese is very rusty now, hihi.)

**Comment by Iseomura** [comment]
Oh! I'm so glad you used Japanese!
It's in poor English, but I'm glad you could read it. Thank you for your continued support.haha.

**Comment by TonkomoLLC** [comment]
Sadly I do not think I will have a result in the morning.
Case 1. Start at time =0  with only one core, OF2112, crashes at time 0.148693 seconds
Case 2. Run with four cores from time = 0 until crash at ~0.27 seconds, and then restart with just one core to ~0.39 seconds. At ~0.39 seconds the time steps were on the order of 1E-60 seconds. 

I stopped the calculation for Case 2 and am restarting at 0.38 seconds on one core. 

I will give an another update in the morning.

おやすみなさい.

**Comment by Iseomura** [comment]
I see...
I'll try to think of a way to make the calculation work.
I'm sorry for making you go through the trouble.
Good night.

**Comment by TonkomoLLC** [comment]
I could only get to ~0.45 seconds but already some particles are beyond the propeller!


![particlesBeyondPropeller-Time0 46](https://user-images.githubusercontent.com/11640748/153863509-1052b248-2a51-4fa7-9dca-03259c3d81b7.png)

If your question is answered I think there is no need to fix the case or do anything else because this may just be a particular situation with the mesh or case setup, not a capability of OpenFOAM v2112. 

Please kindly let me know how you wish me to proceed, or if you think your question is answered.

**Comment by Iseomura** [comment]
Excellent!
I'm not very good at English. Just to confirm, are you saying that if I compile this (link below) MPPICInterDyMfoam in v2112 and do the exact same propeller under the same conditions and procedure, it will improve?
https://github.com/TonkomoLLC/MPPICInterDyMFoam

I can't do anything about it in v2006, can I?

**Comment by TonkomoLLC** [comment]
Yes, I agree with your statement: If you install OpenFOAM v2112, compile MPPICInterDyMFoam at the link above (because the version for v2106 also compiles with v2112 without any changes), and do the exact same propeller case, the result should improve. 

However, if you use the exact same propeller case, you may run into problems with the case crashing. This may be due to many factors, including the mesh, solver parameters, and so on. It may take a while to troubleshoot exactly what the issue is.

You are welcome to write me directly at eadaymo_at_tonkomo.com as well with any follow-up information or questions in case you do not wish to post publicly, here. 

Since the improvement in performance seems to be due to changes in the OpenFOAM  codebase between v2106 and v2112, I suggest you upgrade to v2112. I have no idea how difficult or easy this is for you. 

Lastly, your English is far, far better than my Japanese. 

20年ぐらい前に日本語を勉強しましたが、忘れました。

お疲れ様でした.

**Comment by Iseomura** [comment]
Thank you.
You have been very kind and I think my problem has been solved.
MPPICInterDyMFoam is a very useful solver and I think it will come in handy.
Lastly, I am also typing English with the help of Google Translate. So, the smartest one might be Google, haha.
Thank you very much!

**Comment by TonkomoLLC** [comment]
Good luck and hopefully everything works out. If not please contact me again.
We are fortunate that Google can help translate, hihi.
Cheers,
Eric

**Comment by Iseomura** [comment]
Thank you.
I appreciate it.

Issei
